### ISSUE TITLE
support rewriting import comments

### ISSUE THREAD

**Issue by dmitris** [rogpeppe/govers#1]
Should govers also rewrite the new (added in go1.4) import comments as specified in https://golang.org/s/go14customimport ?

Adding this feature would make govers easier to use for general import path rewriting (for vendoring) besides the version bumping.

**Comment by dmitshur** [comment]
Does [`gomvpkg`](https://godoc.org/golang.org/x/tools/cmd/gomvpkg) do it?

**Comment by dmitris** [comment]
It does - it was also mentioned on https://groups.google.com/d/msg/golang-nuts/tJk6o5_uu-g/rd4bjSM6ffMJ  Closing the issue.
